version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: Tsedenya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tsedenya
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - spring-network
    restart: unless-stopped

networks:
  spring-network:
    driver: bridge

volumes:
  db-data:
